- name: Update AWS EKS kubeconfig
  remote_user: ubuntu
  command:
    cmd: aws eks update-kubeconfig --region us-east-1 --name eks-cluster --profile=eks-creator
  become: false

- name: apt-update
  apt:
    update_cache: yes

- name: install-python3
  package:
    name: python3-pip
    state: present

- name: Install kubernetes
  ansible.builtin.pip:
    name: kubernetes

- name: Copy yaml files 
  ansible.builtin.copy:
    src: '{{item}}'
    dest: '/home/ubuntu'
  loop:
    "{{files}}"

- name: Create resources
  remote_user: ubuntu
  become: false
  kubernetes.core.k8s:
    state: present
    src: '{{item}}'
  loop:
    "{{files}}"