files:
  - namespace.yaml
  - ServiceAccount.yaml
  - deployment.yaml
  - service.yaml

packeges:
  - apt-transport-https 
  - ca-certificates 
  - curl 
  - software-properties-common

docker:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin